### ISSUE TITLE
Issue in pytest-selenium 2.0.0 when using with pytest-xdist

### ISSUE THREAD

**Issue by charith-kulathilaka** [pytest-dev/pytest-selenium#252] opened 2020-08-18 07:29 UTC
I'm using pytest-xdist with pytest- selenium 2.0.0 plugin to run tests in parallel.
Note: Same setup is working fine with pytest-selenium 1.17.0

I'm using following command to run tests.
`pytest --driver Chrome --base-url 'https://example.com' -n 2`

Error:
```
[gw1] darwin -- Python 3.8.3 /Users/admin/workspace/smoke-tests/venv/bin/python3.8

request = <SubRequest 'sensitive_url' for <Function test_should_verify_welcome_page>>, base_url = 'https://example.com'

    @pytest.fixture(scope="session")
    def sensitive_url(request, base_url):
        """Return the first sensitive URL from response history of the base URL"""
        if not base_url:
            return False
        # consider this environment sensitive if the base url or any redirection
        # history matches the regular expression
        urls = [base_url]

        # lazy import requests for projects that don't need requests
        import requests

        try:
            response = requests.get(base_url, timeout=10)
            urls.append(response.url)
            urls.extend([history.url for history in response.history])
        except requests.exceptions.RequestException:
            pass  # ignore exceptions if this URL is unreachable
        search = partial(re.search, request.config.getoption("sensitive_url"))
>       matches = list(map(search, urls))
```

**Comment by Dude-X** [comment] 2020-08-25 01:05
The traceback is incomplete. Can you paste the command line arguments used and the complete traceback?

**Comment by BeyondEvil** [comment] 2020-08-25 07:33
Also, please share header/metadata of a test-run so that we get to see what OS, python version, plugin versions etc. you are on. Thanks!

**Comment by BeyondEvil** [comment] 2020-08-25 08:20
Could this be somehow related to the changes in `pytest-xdist` @Zac-HD ?

That's the only thing I see as a relevant change between 1.17.0 and 2.0.0 of `pytest-selenium` 🤔

**Comment by Zac-HD** [comment] 2020-08-25 10:30
I don't think so - 13e83489ef09312b3f47b0307b8542016acdaee4 is representative of the upstream changes too, we removed the old aliases but didn't actually change any functionality.  It even sounds like this problem happens when varying the `pytest-selenium` version without up/downgrading `pytest-xdist`, but I can't even guess what's happening without more information.

**Comment by BeyondEvil** [comment] 2020-08-25 15:07
I can reproduce it, but I don't have the faintest idea of where to start. Trying to debug `pytest-xdist` is above my knowledge. It seems to swallow any and all print-statements I throw at it. 🤷‍♂️

**Comment by Dude-X** [comment] 2020-08-26 15:09
I am going to debug this today.

**Comment by Dude-X** [comment] 2020-08-26 15:16
`sensitive_url` seems broken by itself when specifying a `base_url`.  Going to dig in deep.

**Comment by Dude-X** [comment] 2020-08-26 15:57
So the interesting thing I've discovered is that the act of setting a `base_url` will automatically mark it as a sensitive url, and it will skip the test if it's not marked nondestructive. In `safety.py` it will skip initializing the sensitive_url config option in xdist so  there is nothing set for sensitive_url config, and that's why it crashes.

Question: Do we want to keep this feature of marking all URLS as sensitive if we set a base_url?

**Comment by Dude-X** [comment] 2020-08-26 17:19
So it seems that when you do specify a `base_url` you have to specify a sensitive url(s) so that it won't get marked for skipping if it's not marked as `nondestructive`. 

I know that xdist recently had a patch to fix how config args are passed between workers so maybe that's what is broken. That being said, I am going to remove the check for being an xdist worker since there's no need to synchronize checking the command line arguments.

**Comment by BeyondEvil** [comment] 2020-08-26 20:40
> Question: Do we want to keep this feature of marking all URLS as sensitive if we set a base_url?

I'm not sure what the original intent was, maybe @davehunt could enlighten us?

But I guess it was to kind of protect the user from himself? To not accidentally do destructive actions in a production environment.

**Comment by davehunt** [comment] 2020-08-28 17:37
This goes back almost 10 years, to when automated tests were accidentally run against Mozilla's live addons website causing many addons to recieve automated ratings and reviews. We introduced a sensitive by default mode, so tests needed to be explicitly marked to indicate if they are not destructive, or the target URL is safe for such tests to run against. If this feature is causing pain, I would encourage a review of the costs and benefits. I certainly wouldn't fight to keep it at this time, but it is possible that users are benefitting from it and removal could cause them some unexpected issues.

**Closed** 2020-09-17 15:27 UTC
Labels: waiting on input
