### ISSUE TITLE
pytest sometimes failed with The browser appears to have exited before we could connect[Random failure]

### ISSUE THREAD

**Issue by HackToday** [pytest-dev/pytest-selenium#80] opened 2016-09-08 07:35 UTC
I applied pytest-selenium in our project, and found a strange issue, the UI test could sometimes failed without any reason, (maybe 1 failure in 10 times) 

Environment is:
```
Firefox 45.0.2
pytest-selenium==1.3.1
selenium==2.53.6
```

Following is the error message:

```
.E

==================================== ERRORS ====================================

request = <SubRequest 'selenium' for <Function 'test_app_edit'>>

    @pytest.fixture
    def selenium(request):
        """Returns a WebDriver instance based on options and capabilities"""
        driver_type = request.config.getoption('driver')
        if driver_type is None:
            raise pytest.UsageError('--driver must be specified')
    
        driver_fixture = '{0}_driver'.format(driver_type.lower())
>       driver = request.getfuncargvalue(driver_fixture)

/usr/lib/python2.7/site-packages/pytest_selenium/pytest_selenium.py:82: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/usr/lib/python2.7/site-packages/pytest_selenium/drivers/firefox.py:46: in firefox_driver
    return Firefox(**kwargs)
/usr/lib/python2.7/site-packages/selenium/webdriver/firefox/webdriver.py:80: in __init__
    self.binary, timeout)
/usr/lib/python2.7/site-packages/selenium/webdriver/firefox/extension_connection.py:52: in __init__
    self.binary.launch_browser(self.profile, timeout=timeout)
/usr/lib/python2.7/site-packages/selenium/webdriver/firefox/firefox_binary.py:68: in launch_browser
    self._wait_until_connectable(timeout=timeout)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <selenium.webdriver.firefox.firefox_binary.FirefoxBinary object at 0x2885450>
timeout = 30

    def _wait_until_connectable(self, timeout=30):
        """Blocks until the extension is connectable in the firefox."""
        count = 0
        while not utils.is_connectable(self.profile.port):
            if self.process.poll() is not None:
                # Browser has exited
                raise WebDriverException(
>                   "The browser appears to have exited "
                    "before we could connect. If you specified a log_file in "
                    "the FirefoxBinary constructor, check it for details.")
E               WebDriverException: Message: The browser appears to have exited before we could connect. If you specified a log_file in the FirefoxBinary constructor, check it for details.

/usr/lib/python2.7/site-packages/selenium/webdriver/firefox/firefox_binary.py:99: WebDriverException
!!!!!!!!!!!!!!!!!!!! Interrupted: stopping after 1 failures !!!!!!!!!!!!!!!!!!!!
====================== 3 passed, 1 error in 39.18 seconds ======================

```

I can not tell how to reproduce that, that's what puzzled me also.
Given that it have error trace from pytest_selenium,  I did not think it was from selenium itself. So open a issue here.

Thanks

**Comment by RonnyPfannschmidt** [comment] 2016-09-08 07:50
the traceback hooks deep into selenium, and the exception orginates in the selenium package

**Comment by HackToday** [comment] 2016-09-08 08:53
It would be helpful if someone can tell what could be the reason for such issue.

**Comment by davehunt** [comment] 2016-09-08 10:21
The reason is given in your trace: "WebDriverException: Message: The browser appears to have exited before we could connect." this suggests that Firefox was closed or crashed during the test. Can you provide the command line you're using to run these tests, and anything else that might help me to reproduce it such as what operating system you're using, and if there are any additional configuration options specified anywhere? Also, can you try running with Firefox 47.0.1 to see if you can still replicate the issue?

**Comment by HackToday** [comment] 2016-09-09 04:38
1> for you questions, 
- the OS is CentOS 7.2,  
- for tests, it was just simple test our application, not anything special
- for run commandline it is simple like this:
  
```
py.test --base-url http://127.0.0.1:8000 --driver Firefox mytest  -x
```

2> For firefox 47.0.*  I could also find some issues from the web . like this 

https://snakeycode.wordpress.com/category/selenium/

From that link it also talked about issue like 
"WebDriverException: Message: The browser appears to have exited before we could connect" 

seems suggest use this way 
https://developer.mozilla.org/en-US/docs/Mozilla/QA/Marionette/WebDriver

I will try if Marionette could solve the issue or not.

**Comment by davehunt** [comment] 2016-09-09 10:39
You could try to replicate your issue without using pytest-selenium by creating a python script that just launches Firefox a number of times. From your traceback it doesn't look like this is an issue with the plugin, and reproducing without the plugin would help to identify the issue in Selenium, which you can raise here: https://github.com/SeleniumHQ/selenium/issues

That said, for Firefox 48 and above it is necessary to use Marionette and GeckoDriver (as you mention), and if you can get that to work then this issue may no longer be a concern. I'm going to close this for now. Please reopen if you have more evidence that pytest-selenium if the cause of the issue.

**Closed by davehunt** 2016-09-09 10:39 UTC
