### ISSUE TITLE
get_cookies() is empty

### ISSUE THREAD

**Issue by Bobspadger** [pytest-dev/pytest-selenium#194] opened 2018-09-24 16:22 UTC
Hi All

I have a test suite which is working nicely when using standard desktop browser settings. (Chrome)

When I try to test as a mobile using the following options, pytest-selenium returns no cookies.

```python
@pytest.fixture()
def chrome_options(chrome_options):
    mobile_emulation = { "deviceName": "iPhone 6/7/8" }
    chrome_options.add_experimental_option('mobileEmulation', mobile_emulation)
    return chrome_options
```

Am I missing something? (I've tried even just opening `google.com` and nothing is shown, but on inspection in the web inspector, I can see cookies.

**Comment by Bobspadger** [comment] 2018-09-25 08:58
as an update to this, testing it just with selenium and cookies are returned.

my setup for that is as follows:



```python
from selenium import webdriver
options = webdriver.ChromeOptions()
options.add_argument('--ignore-certificate-errors')
options.add_argument("--test-type")
options.binary_location = "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"
mobile_emulation = { "deviceName": "iPhone 6/7/8" }
options.add_experimental_option('mobileEmulation', mobile_emulation)

driver = webdriver.Chrome(chrome_options=options)
driver.switch_to_window(driver.current_window_handle)
driver.get(BASE_URL)

driver.get_cookies()

```

**Comment by BeyondEvil** [comment] 2018-09-25 23:05
Thank for reporting this @Bobspadger and thanks for the repro-case.

Question: In the non pytest-selenium snippet, you have more arguments than in the `chrome_options` fixture. Does that play any part in the issue you're seeing?

**Comment by BeyondEvil** [comment] 2018-09-26 09:04
@Bobspadger Just to avoid any confusion, are you running Remotely or locally? Mind sharing the contents of your environment? (pip freeze)

**Comment by Bobspadger** [comment] 2018-09-26 09:19
@BeyondEvil I'm running this all locally.

```
atomicwrites==1.2.1
attrs==18.2.0
certifi==2018.8.24
chardet==3.0.4
idna==2.7
more-itertools==4.3.0
pluggy==0.7.1
py==1.6.0
pytest==3.8.1
pytest-base-url==1.4.1
pytest-html==1.19.0
pytest-metadata==1.7.0
pytest-selenium==1.14.0
pytest-variables==1.7.1
requests==2.19.1
selenium==3.14.1
six==1.11.0
urllib3==1.23```

This is running in a virtual environment

```
chromedriver --version
ChromeDriver 2.42.591059 (a3d9684d10d61aa0c45f6723b327283be1ebaad8)```

```
Chrome
Version 69.0.3497.100 (Official Build) (64-bit)
```

**Comment by Bobspadger** [comment] 2018-09-26 09:27
For additional info, when using pycharms debugger on the test, and pausing to step through, I can use Chromes inspector to check cookies returned (and Chrome does not have them either, which is very strange, but manually doing the test and it does have them)


The only difference I can see is shown in the following images.

Using Pytest-selenium
![screenshot 2018-09-25 at 17 26 05](https://user-images.githubusercontent.com/1614970/46070855-adbdd100-c176-11e8-8628-799437c93345.png)

Using Chrome normally
![screenshot 2018-09-25 at 17 27 51](https://user-images.githubusercontent.com/1614970/46070875-b57d7580-c176-11e8-8b91-051444b90b08.png)

**Comment by BeyondEvil** [comment] 2018-09-29 18:37
So, there's a couple things going on here.

Running your code, I get cookies using both the "selenium only" and "pytest-selenium":

```
@pytest.fixture()
def chrome_options(chrome_options):
    mobile_emulation = { "deviceName": "iPhone 6/7/8" }
    chrome_options.add_experimental_option('mobileEmulation', mobile_emulation)
    return chrome_options


@pytest.mark.tags("indev")
def test_dual(selenium):
    from selenium import webdriver

    BASE_URL = 'https://www.google.com'
    options = webdriver.ChromeOptions()
    options.add_argument('--ignore-certificate-errors')
    options.add_argument("--test-type")
    options.binary_location = "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"
    mobile_emulation = {"deviceName": "iPhone 6/7/8"}
    options.add_experimental_option('mobileEmulation', mobile_emulation)

    driver = webdriver.Chrome(chrome_options=options)
    driver.switch_to_window(driver.current_window_handle)
    driver.get(BASE_URL)

    print("")
    print("Selenium only:", driver.get_cookies())
    driver.quit()

    selenium.get(BASE_URL)
    print("Pytest-selenium:", selenium.get_cookies())
    selenium.quit()
```

Output:

```
Selenium only: [{'domain': '.google.com', 'expiry': 2145916797.053683, 'httpOnly': False, 'name': 'CONSENT', 'path': '/', 'secure': False, 'value': 'WP0.271e9f'}, {'domain': '.google.com', 'expiry': 1554057269.053623, 'httpOnly': True, 'name': 'NID', 'path': '/', 'secure': False, 'value': '140=xhqIH-fB62XJVBFukXOPmLDLQePRTeMx0NfAHBXymJXonWGHliCmpkcZ6mCbHl5LenyogUmIkqyj73gk01_Bxvq7McKhCR9Bg1KXPqID4GcA3OAi3vxAE4qaxcEqmPDh'}, {'domain': '.google.com', 'expiry': 1540838069.053542, 'httpOnly': False, 'name': '1P_JAR', 'path': '/', 'secure': False, 'value': '2018-09-29-18'}]
```
and
```
Pytest-selenium: [{'domain': '.google.com', 'expiry': 2145916797.411893, 'httpOnly': False, 'name': 'CONSENT', 'path': '/', 'secure': False, 'value': 'WP0.271e9f'}, {'domain': '.google.com', 'expiry': 1554057270.411785, 'httpOnly': True, 'name': 'NID', 'path': '/', 'secure': False, 'value': '140=vEv8aTELt1pSjcQZsAMe33w-YBrrC0o-0iI7kzomgqfg2220Xwns8rG5i5qa1WeIMBfxZ1270AdBYmTzaK5V1Wqr4wcei3l9xu5TcCpxrfsQmtr7nwYZx0lRKyr-3x-o'}, {'domain': '.google.com', 'expiry': 1540838071.152417, 'httpOnly': False, 'name': '1P_JAR', 'path': '/', 'secure': False, 'value': '2018-09-29-18'}]
```

What is true for both, is that it doesn't seem to activate a "true" emulation mode with the correct device. But for that you would have to raise an issue with the chrome-folks.

**Comment by Bobspadger** [comment] 2018-10-02 11:15
odd, because I don't get cookies for the first way using pytest.

Oh well - I'll keep digging to see if there is a reason for it.

**Comment by BeyondEvil** [comment] 2018-10-22 07:59
Did you manage to solve it @Bobspadger ?

**Comment by Bobspadger** [comment] 2018-10-22 09:00
@BeyondEvil sadly no , can't get to the bottom of it!

I've had to work on some other projects, but should be looking at this again next week.

**Comment by Bobspadger** [comment] 2018-10-22 09:01
@BeyondEvil sadly no.

I've been working on other projects but should be looking at this again next week.

**Comment by BeyondEvil** [comment] 2019-04-27 09:37
Any progress on this @Bobspadger ? Anything I can do to help?

**Comment by Bobspadger** [comment] 2019-04-29 08:33
@BeyondEvil I'm afraid I've not had any time to check into this since then.

I'm not sure when I might get back to this i'm afraid!

**Comment by BeyondEvil** [comment] 2019-04-29 20:18
Let's close it then, and if the issue is still there whenever you get a chance to look at it again we can re-open it. :)

**Closed by BeyondEvil** 2019-04-29 20:18 UTC
