### ISSUE TITLE
Selenium Hub - Remote Webdriver not apart of hub’s docker network 

### ISSUE THREAD

**Issue by daniel-butler** [pytest-dev/pytest-selenium#231] opened 2020-02-14 05:34 UTC
Here is a [GitHub Repo](https://github.com/daniel-butler/selenium-grid-flask-tests) with a simple test to illustrate the issue in the title. Essentially, sending a remote webdriver `get` request to a container in the same network returns the chromiums default page. The only reason I can figure the default page is shown is the request isn’t getting to the app container. 

Selenium’s webdriver can ping google and it can ping the app container’s host ip. Accessing the container from the host ip has the drawback, that the app isn’t setup to accept its host’s IP as a hostname/server so the request is rejected. Should the app only be accessible by the container’s host IP? If I need to explain what I mean by host IP I can give more detail. 

The problem seems to be with how pytest selenium executes the remote webdriver.  `curl`ing from the node container to the app works just fine.

**Comment by BeyondEvil** [comment] 2020-02-14 22:49
If I have understood the problem correct, I think this is a Docker thing - and not a Selenium or a plug thing.

Now, unfortunately, I'm not exactly sure what the cure is.

The problem is that the browser in selenium node is trying to reach `localhost:5000`, which doesn't work. Because localhost only refers to the node container. So you will have to make sure it's that the domain it's trying to reach is instead `app:5000`.

HOWEVER, that doesn't seem to work - and I have no idea why.

Here's what I did to test

Expose port 5900 of the selenium-node (node) and VNC into it (you can download vnc viewer):

Edit `docker-compose.yml`
```yml
  selenium-chrome:
    image: selenium/node-chrome-debug
    stdin_open: true
    ports:
      - "5900:5900"
    links:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
```
Run your `up` command then direct VNC Viewer to `localhost:5900`, password is `secret`.
(You can later view here to see what happens when the test runs).

Install ping in the node:
- Right click the desktop.
- Applications > Shells > Bash
- Run:

```bash
sudo apt-get update
sudo apt-get install iputils-ping
``` 

Now you can `ping app` which gives you the IP.

Open Chrome:
- Right click the desktop.
- Applications > Network > Web Browsing > Google Chrome

If you input `<IP>:5000` you'll get `Hello`, if you input `app:5000`, you won't.

And I have no idea why. :(

**Comment by BeyondEvil** [comment] 2020-02-14 23:27
Ok, this is so weird.

If I change the name from `app` to something else, I used `webservice` (`webservice:5000`) it works as expected.

But the root problem still remains, the url has to be `webservice`, not `localhost`.

**Comment by BeyondEvil** [comment] 2020-02-20 17:19
ping @daniel-butler

**Comment by daniel-butler** [comment] 2020-02-24 05:43
Hey I apologize for not getting back sooner. I’ve been busy at work and had to put this off. I should be able to look into this is two weeks. 

I was planning on trying to use selenium’s remote web driver directly to see if there was a capabilities setting or something related that is causing the issue. Talking with selenium team they said it should be working.

**Comment by BeyondEvil** [comment] 2020-03-14 14:48
Any news on this @daniel-butler ?

**Comment by BeyondEvil** [comment] 2020-05-13 13:09
Closing this for now as I'm fairly sure this isn't related to the plugin itself.

Feel free to re-open.

**Closed by BeyondEvil** 2020-05-13 13:09 UTC
Labels: waiting on input
