### ISSUE TITLE
"Driver Log" appears two times in html report links

### ISSUE THREAD

**Issue by abotalov** [pytest-dev/pytest-selenium#159] opened 2018-04-14 16:10 UTC
"Driver log" is inserted two times into "Links" section of html report.
First time in `_gather_driver_log` function.
Second time in `_gather_logs` function (as `driver.log_types` returns `driver` as well).

**Comment by davehunt** [comment] 2018-04-16 09:38
The first is the log directly from the driver executable, and the second is the one provided by the driver via the Selenium API. Could you confirm if the content of these is identical? Are you using Google Chrome? I don't think any of the other drivers support the Selenium logging API (which is not in the WebDriver specification). Would you prefer the driver log is skipped from the Selenium API, or renamed?

**Comment by abotalov** [comment] 2018-04-18 09:30
Well, in case of the following script:
```python
import json

from selenium import webdriver
from selenium.webdriver import DesiredCapabilities

caps = DesiredCapabilities.CHROME
caps["loggingPrefs"] = {"driver": "INFO"}
driver = webdriver.Chrome(desired_capabilities=caps,
                          service_log_path="service_log.txt")

driver.get("https://www.google.com")
with open("driver_log.txt", "w") as f:
  text = json.dumps(driver.get_log("driver"), indent=4)
  f.write(text)
driver.quit()
```

"service_log.txt" and "driver_log.txt" contain almost the same data. The only difference is that "service_log.txt" contains also `COMMAND InitSession`, `COMMAND Quit` and `RESPONSE Quit` that "driver_log.txt" does not contain.

But in case of Pytest-Selenium service_log does not contain the large portion of the end of the log.

I believe the reason is that Chromedriver buffers output that gets into service log.
I think Pytest-Selenium should get driver log only once (using `service_log_path` and after calling `driver.quit()`)

**Comment by BeyondEvil** [comment] 2019-04-27 09:36
Is this still a problem @abotalov ? If that's the case, would you consider contributing a fix based on the above discussion?

Cheers!

**Comment by BeyondEvil** [comment] 2020-03-15 11:59
I'm going to close this issue due to lack of interaction. If you're still seeing this and can successfully reproduce it - feel free to reopen.

**Closed by BeyondEvil** 2020-03-15 11:59 UTC
Labels: bug, help wanted
