### ISSUE TITLE
pluggy throws assert not self.has_spec()

### ISSUE THREAD

**Issue by pawciobiel** [pytest-dev/pytest-selenium#134] opened 2017-10-07 06:20 UTC
Hi,

Thanks for all the work.
I can't seam to be able to get it working. For some reason it throws AssertionError.
Could someone help please?

In **conftest.py** I have:
```
pytest_plugins = ['pytest_selenium', ]
```

`D:\ >pytest test_pythonorg.py`

```
Traceback (most recent call last):
  File "C:\Python27\Scripts\pytest-script.py", line 9, in <module>
    load_entry_point('pytest==3.2.3', 'console_scripts', 'pytest')()
  File "C:\Python27\lib\site-packages\_pytest\config.py", line 49, in main
    config = _prepareconfig(args, plugins)
  File "C:\Python27\lib\site-packages\_pytest\config.py", line 168, in _preparec
onfig
    pluginmanager=pluginmanager, args=args)
  File "C:\Python27\lib\site-packages\_pytest\vendored_packages\pluggy.py", line
745, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "C:\Python27\lib\site-packages\_pytest\vendored_packages\pluggy.py", line
339, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "C:\Python27\lib\site-packages\_pytest\vendored_packages\pluggy.py", line
334, in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
  File "C:\Python27\lib\site-packages\_pytest\vendored_packages\pluggy.py", line
613, in execute
    return _wrapped_call(hook_impl.function(*args), self.execute)
  File "C:\Python27\lib\site-packages\_pytest\vendored_packages\pluggy.py", line
250, in _wrapped_call
    wrap_controller.send(call_outcome)
  File "C:\Python27\lib\site-packages\_pytest\helpconfig.py", line 68, in pytest
_cmdline_parse
    config = outcome.get_result()
  File "C:\Python27\lib\site-packages\_pytest\vendored_packages\pluggy.py", line
280, in get_result
    _reraise(*ex)  # noqa
  File "C:\Python27\lib\site-packages\_pytest\vendored_packages\pluggy.py", line
265, in __init__
    self.result = func()
  File "C:\Python27\lib\site-packages\_pytest\vendored_packages\pluggy.py", line
614, in execute
    res = hook_impl.function(*args)
  File "C:\Python27\lib\site-packages\_pytest\config.py", line 957, in pytest_cm
dline_parse
    self.parse(args)
  File "C:\Python27\lib\site-packages\_pytest\config.py", line 1121, in parse
    self._preparse(args, addopts=addopts)
  File "C:\Python27\lib\site-packages\_pytest\config.py", line 1092, in _prepars
e
    args=args, parser=self._parser)
  File "C:\Python27\lib\site-packages\_pytest\vendored_packages\pluggy.py", line
745, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "C:\Python27\lib\site-packages\_pytest\vendored_packages\pluggy.py", line
339, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "C:\Python27\lib\site-packages\_pytest\vendored_packages\pluggy.py", line
334, in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
  File "C:\Python27\lib\site-packages\_pytest\vendored_packages\pluggy.py", line
613, in execute
    return _wrapped_call(hook_impl.function(*args), self.execute)
  File "C:\Python27\lib\site-packages\_pytest\vendored_packages\pluggy.py", line
254, in _wrapped_call
    return call_outcome.get_result()
  File "C:\Python27\lib\site-packages\_pytest\vendored_packages\pluggy.py", line
280, in get_result
    _reraise(*ex)  # noqa
  File "C:\Python27\lib\site-packages\_pytest\vendored_packages\pluggy.py", line
265, in __init__
    self.result = func()
  File "C:\Python27\lib\site-packages\_pytest\vendored_packages\pluggy.py", line
614, in execute
    res = hook_impl.function(*args)
  File "C:\Python27\lib\site-packages\_pytest\config.py", line 1003, in pytest_l
oad_initial_conftests
    self.pluginmanager._set_initial_conftests(early_config.known_args_namespace)
 
  File "C:\Python27\lib\site-packages\_pytest\config.py", line 325, in _set_init
ial_conftests
    self._try_load_conftest(anchor)
  File "C:\Python27\lib\site-packages\_pytest\config.py", line 331, in _try_load
_conftest
    self._getconftestmodules(anchor)
  File "C:\Python27\lib\site-packages\_pytest\config.py", line 345, in _getconft
estmodules
    clist = self._getconftestmodules(path.dirpath())
  File "C:\Python27\lib\site-packages\_pytest\config.py", line 356, in _getconft
estmodules
    mod = self._importconftest(conftestpath)
  File "C:\Python27\lib\site-packages\_pytest\config.py", line 392, in _importco
nftest
    self.consider_conftest(mod)
  File "C:\Python27\lib\site-packages\_pytest\config.py", line 415, in consider_
conftest
    self.register(conftestmodule, name=conftestmodule.__file__)
  File "C:\Python27\lib\site-packages\_pytest\config.py", line 270, in register
    self.consider_module(plugin)
  File "C:\Python27\lib\site-packages\_pytest\config.py", line 421, in consider_
module
    self._import_plugin_specs(getattr(mod, 'pytest_plugins', []))
  File "C:\Python27\lib\site-packages\_pytest\config.py", line 426, in _import_p
lugin_specs
    self.import_plugin(import_spec)
  File "C:\Python27\lib\site-packages\_pytest\config.py", line 458, in import_pl
ugin
    self.register(mod, modname)
  File "C:\Python27\lib\site-packages\_pytest\config.py", line 264, in register
    ret = super(PytestPluginManager, self).register(plugin, name)
  File "C:\Python27\lib\site-packages\_pytest\vendored_packages\pluggy.py", line
371, in register
    hook._maybe_apply_history(hookimpl)
  File "C:\Python27\lib\site-packages\_pytest\vendored_packages\pluggy.py", line
768, in _maybe_apply_history
    res = self._hookexec(self, [method], kwargs)
  File "C:\Python27\lib\site-packages\_pytest\vendored_packages\pluggy.py", line
339, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "C:\Python27\lib\site-packages\_pytest\vendored_packages\pluggy.py", line
334, in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
  File "C:\Python27\lib\site-packages\_pytest\vendored_packages\pluggy.py", line
614, in execute
    res = hook_impl.function(*args)
  File "build\bdist.win32\egg\pytest_selenium\pytest_selenium.py", line 36, in p
ytest_addhooks
  File "C:\Python27\lib\site-packages\_pytest\vendored_packages\pluggy.py", line
430, in add_hookspecs
    hc.set_specification(module_or_class, spec_opts)
  File "C:\Python27\lib\site-packages\_pytest\vendored_packages\pluggy.py", line
700, in set_specification
    assert not self.has_spec()
AssertionError
```

Thanks.

**Comment by RonnyPfannschmidt** [comment] 2017-10-07 07:44
pytest-selenium will automatically be actuve, if its being added twice that causes trouble for the plugin manager

the error message could indeed be better

if you use it as intended you shouldnt need the extra line enabling it

**Comment by davehunt** [comment] 2017-10-12 18:25
@pawciobiel let us know if @RonnyPfannschmidt's comment helped. If I don't hear from you I'll go ahead and close the issue. Thanks!

**Comment by davehunt** [comment] 2017-12-05 14:30
Closing as no response in over 30 days.

**Closed by davehunt** 2017-12-05 14:30 UTC
Labels: question
