### ISSUE TITLE
Damaged screenshot files saved in HTML report assets folder on OSX

### ISSUE THREAD

**Issue by rbwinslow** [pytest-dev/pytest-selenium#79] opened 2016-09-07 21:01 UTC
The PNG files that pytest-selenium writes to the "assets" folder that it creates in support of its HTML report cannot be opened on OSX 10.11.6. This is pytest-selenium 1.3.1 with selenium 2.53.6 as installed via pip, running under Python 3.5.1 and using --driver Firefox.

The images are displayed as broken image icons in the report, and attempts to open the PNG files directly produce "The file (long, randomized name).png could not be opened … it may be damaged or use a file format that Preview doesn't recognize" from Preview. The image files are not empty; one of them is 111 KB in size and the other is 3.8 MB.

When I use the WebDriver's save_screenshot method (from the "selenium" fixture) directly at the end of my tests, it saves undamaged and correct screenshot PNG images (36 KB and 1.3 MB). In this case, the tests are successful, while I intentionally made tests fail in order to produce screenshots in pytest-selenium's HTML report.

**Comment by davehunt** [comment] 2016-09-09 10:51
I wonder if this is a python 3 issue with [pytest-html](https://github.com/pytest-dev/pytest-html) or selenium. Can you try the `get_screenshot_as_base64` method to see if that return a valid screenshot in base64?

**Comment by rbwinslow** [comment] 2016-09-09 17:52
I tried `get_screenshot_as_base64` (writing the bytes to disk) and it produced a valid PNG file, unlike `save_screenshot`.

**Comment by davehunt** [comment] 2016-09-12 11:31
Sorry, you said in your earlier comment that `save_screenshot` saves "undamaged and correct screenshot PNG images" but in your latest comment you say that `get_screenshot_as_base64` produces a valid PNG file "unlike `save_screenshot`. Could you clarify what is and isn't working when using the WebDriver object directly?

**Comment by rbwinslow** [comment] 2016-09-12 17:54
So sorry for my inattentive and confusing post! My **original** testimony was correct, and in my more recent comment I had been _thinking_ about the pytest-selenium behavior, but _wrote_ `save_screenshot` instead, unthinkingly. `save_screenshot` does, indeed, work correctly (as does `get_screenshot_as_base64`). It's only the pytest-selenium HTML report that produces damaged screenshot files.

I also ran some experiments in our build pipeline, which is hosted in [this Docker image](https://hub.docker.com/_/jenkins/) on a multi-container environment on Amazon, so that I could view screenshots generated under Linux (I believe the image is Debian Jessie). The results were identical to those under OSX: the HTML report produces damaged (though non-empty) files, as seen both remotely, viewing the HTML reports via Jenkins, and locally, after downloading one. The `save_screenshot` function produced perfectly normal files in Linux, as it did under OSX.

**Comment by rarelam** [comment] 2016-09-13 10:01
I facing this issue too. All the images are unable to view with neither browser nor photo viewer.

I run my test cases in window environment:
1) run the test locally, then the images were fine.
2) If I run my test with cygwin, then the image saved will be corrupted, which described on the beginning by @rbwinslow.

I think the issue is happen with linux command/ environment which causing the image broken. But not too sure as I don't have ubuntu VM setup.

**Comment by rarelam** [comment] 2016-09-13 10:06
forget to mention, I was using python 2.7.3
pytest 3.0.1, with plugins html 1.9.0, selenium 1.3.1, base-url 1.1.0

**Comment by davehunt** [comment] 2016-09-14 15:55
Thanks for the details @rbwinslow and @rarelam. So it sounds like it's not a python 3.x issue then. I suspect either pytest-selenium is getting a corrupt image from selenium, or that the image is being corrupted when it's passed to pytest-html, or that pytest-html is somehow writing the base64 image to disk as a corrupt PNG. Of these, I think pytest-html is most likely to be the cause, however let's leave the issue here until we can confirm that.

@SIlne30 is going to look into this for me. Let's see if we can first replicate this ourselves, and then debug both pytest-selenium and pytest-html to see which point the image becomes corrupt.

**Comment by rbwinslow** [comment] 2016-09-14 18:47
Thank you very much, @rarelam and @silne30, for looking into this.

**Comment by silne30** [comment] 2016-09-15 16:14
I ran this under selenium 3.0.0 beta2 and did not get a damaged file on Mac OSX 10.11.6. Downgrading to 2.53.6 to see if selenium may be the issue.

**Comment by silne30** [comment] 2016-09-17 00:36
I cannot reproduce this behavior using a mac on either Firefox 46.0.1 running Selenium 2.53.6 nor Firefox 48 running Selenium 3.0.0b2.

**Comment by silne30** [comment] 2016-09-17 00:36
This was all under python 2.7.

@rbwinslow Do you have any other information that can help me troubleshoot or reproduce this?

**Comment by rbwinslow** [comment] 2016-09-20 18:39
@silne30 : Gathering information in response to your request, I saw that my Firefox installation was back at 41.0.1, so I upgraded in hopes of experimenting with the same configurations that worked successfully for you. After spending some time and being frustrated [by](https://github.com/mozilla/geckodriver/issues/56#issuecomment-248097078) [several](https://github.com/mozilla/geckodriver/issues/113) [issues](https://github.com/mozilla/geckodriver/issues/144) I eventually gave up on getting Marionette operational with my tests.

After downgrading everything and restoring stable execution, here's what my `pip freeze` looks like:

```
py==1.4.31
pytest==2.9.2
pytest-base-url==1.1.0
pytest-html==1.10.0
pytest-selenium==1.3.1
pytest-variables==1.4
requests==2.11.1
selenium==2.53.6
```

My Firefox version is now 47.0.1, and the end result is still damaged PNG files in the HTML report assets directory. Are there other kinds of dependencies that I can dump that might be helpful?

**Comment by davehunt** [comment] 2016-09-23 09:48
I've been able to replicate this. Looking into it now.

**Comment by davehunt** [comment] 2016-09-23 09:54
Works for me with python 2.7.12, but fails with python 3.5.2.

**Comment by davehunt** [comment] 2016-09-23 10:05
This is definitely an issue with pytest-html, let's close this and move updates to https://github.com/pytest-dev/pytest-html/issues/78

**Closed by davehunt** 2016-09-23 10:05 UTC

**Comment by davehunt** [comment] 2016-09-23 13:19
@rbwinslow could you try installing the v1.10.1 release candidate of pytest-html and let me know if the issue is fixed? pip install --upgrade --pre pytest-html

**Comment by rbwinslow** [comment] 2016-09-23 17:33
_Et voila,_ it works. Thank you so much, @davehunt and @silne30, for all of the work!

**Comment by silne30** [comment] 2016-09-23 17:59
Awesome job debugging @davehunt!


[image: photo]
*John Dorlus*
Senior Software Engineer in Test, Mozilla Corporation
m:407.780.8031 | e:jdorlus@mozilla.org | w:http://www.mozilla.org | a:331
E. Evelyn Avenue Mountain View, CA 94041 USA
<http://www.facebook.com/mozilla>  <http://www.linkedin.com/in/johndorlus>
<http://www.twitter.com/the_power_coder>  <http://www.github.com/silne30>
<http://www.facebook.com/mozilla> <https://twitter.com/mozilla>
<http://www.linkedin.com/company/mozilla-corporation>
Get a signature like this: Click here!
<http://ws-promos.appspot.com/r?rdata=eyJydXJsIjogImh0dHA6Ly93d3cud2lzZXN0YW1wLmNvbS9lbWFpbC1pbnN0YWxsP3dzX25jaWQ9NjcyMjk0MDA4JnV0bV9zb3VyY2U9ZXh0ZW5zaW9uJnV0bV9tZWRpdW09ZW1haWwmdXRtX2NhbXBhaWduPXByb21vXzU3MzI1Njg1NDg3Njk3OTIiLCAiZSI6ICI1NzMyNTY4NTQ4NzY5NzkyIn0=&u=994992731401215>

**Comment by davehunt** [comment] 2016-09-23 18:37
@rbwinslow great! I'll release a new version of pytest-html on Monday.

**Comment by davehunt** [comment] 2016-09-23 21:35
Decided to do it today - https://pypi.python.org/pypi/pytest-html/1.10.1

**Comment by ramonasuciu** [comment] 2017-09-27 14:37
I am able still to reproduce this issue, using pytest-html==1.16.0.
When running locally, on a Mac, the png files are valid (I am using save_screenshot()).
However, when running the tests from Bamboo (which runs on Windows), I get corrupted png files, which cannot be added to the html report.

**Comment by ramonasuciu** [comment] 2017-09-28 11:06
It was a matter of incorrectly defining where to save the screenshots, and how to use them as shared artifacts from Bamboo (which is running on Windows, hence a whole new range of issues).
It now works if using the default assets/ folder.
