### ISSUE TITLE
Dependency conflicts

### ISSUE THREAD

**Issue by jrbenny35** [pytest-dev/pytest-selenium#268] opened 2021-08-06 18:45 UTC
Recently I noticed some errors where pytest-selenium needs tenacity older than version 7 but newer than or equal to version 6. Tenacity has a version 7.0.0. Can we change pytest-selenium to use tenacity version 7 or does it need to use a version older than 7.0.0.

**Comment by lordgordon** [comment] 2021-08-10 13:11
Tenacity now has a version `8.x`: https://github.com/jd/tenacity/releases/tag/8.0.1

**Comment by lordgordon** [comment] 2021-08-11 08:57
I submitted a PR to support newest versions of Tenacity. Local testing looks good.

**Comment by BeyondEvil** [comment] 2021-08-31 22:18
> I submitted a PR to support newest versions of Tenacity. Local testing looks good.

Thank you, will review shortly!

**Comment by lordgordon** [comment] 2021-11-02 10:09
This is now fixed thanks to the migration to Poetry.

**Comment by BeyondEvil** [comment] 2021-11-02 12:28
Should be fixed by migration to Poetry.

**Closed by BeyondEvil** 2021-11-02 12:28 UTC

**Comment by jgb** [comment] 2022-10-26 08:17
@BeyondEvil hello, sorry to reopen this, but are you sure this is fixed?
I've run into some dependency conflicts like this:

The conflict is caused by:
    luigi 3.1.1 depends on tenacity<9 and >=8
    plotly 5.10.0 depends on tenacity>=6.2.0
    pytest-selenium 4.0.0 depends on tenacity<7.0.0 and >=6.0.0

This is with pytest-selenium v4.0.0

**Comment by sallner** [comment] 2022-10-26 08:23
It seems that in principle the version constraints were relaxed, but the respective code was not released yet. I would also love to see a release. Is there anything blocking that, where some help could speed up the process? @BeyondEvil

**Comment by BeyondEvil** [comment] 2022-10-26 08:57
What @sallner said. The fix is on master, but not yet released @jgb 

Technically I can release it, but I wanted to properly support Selenium 4 as that is what was promised for the v4 release of the plugin. But it seems I'm going to have to make some breaking changes in a minor or patch release (as the plan is that the version of the pluging should be in parity with the selenium version).

Essentially I was too fast on the trigger. :(

I would _really_ appreciate some help on that @sallner - mostly some rubber-ducking on design/implementation decisions. 🙇

**Comment by BeyondEvil** [comment] 2022-10-26 09:08
I had asked a question that I never got a response for @sallner https://github.com/pytest-dev/pytest-selenium/pull/300#issuecomment-1258434619
